import { Button } from "@/components/ui/button";
import { Copy, Save, Check, FileJson, FileText } from "lucide-react";
import { useState } from "react";
import { toast } from "@/hooks/use-toast";
import type { PromptHistoryItem } from "@/lib/promptEnhancer";

interface ExportActionsProps {
  original: string;
  improved: string;
  onSave: () => void;
  history: PromptHistoryItem[];
}

export function ExportActions({
  original,
  improved,
  onSave,
  history,
}: ExportActionsProps) {
  const [copied, setCopied] = useState(false);

  const copyToClipboard = async () => {
    if (!improved) return;

    await navigator.clipboard.writeText(improved);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast({
      title: "Copied!",
      description: "Improved prompt copied to clipboard",
    });
  };

  const exportAsMarkdown = () => {
    if (!improved) return;

    const markdown = `# Prompt Improvement

## Original Prompt
${original}

## Improved Prompt
${improved}

---
*Generated by Prompt Improver AI*
`;

    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "improved-prompt.md";
    a.click();
    URL.revokeObjectURL(url);

    toast({
      title: "Exported!",
      description: "Prompt exported as Markdown",
    });
  };

  const exportHistoryAsJSON = () => {
    if (history.length === 0) {
      toast({
        title: "No history",
        description: "There's no history to export",
        variant: "destructive",
      });
      return;
    }

    const blob = new Blob([JSON.stringify(history, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "prompt-history.json";
    a.click();
    URL.revokeObjectURL(url);

    toast({
      title: "Exported!",
      description: "History exported as JSON",
    });
  };

  return (
    <div className="flex flex-wrap gap-2">
      <Button
        variant="default"
        size="sm"
        onClick={copyToClipboard}
        disabled={!improved}
        className="gap-2 rounded-xl shadow-md hover:shadow-lg transition-shadow"
      >
        {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
        {copied ? "Copied!" : "Copy"}
      </Button>

      <Button
        variant="secondary"
        size="sm"
        onClick={onSave}
        disabled={!improved}
        className="gap-2 rounded-xl"
      >
        <Save className="h-4 w-4" />
        Save
      </Button>

      <Button
        variant="outline"
        size="sm"
        onClick={exportAsMarkdown}
        disabled={!improved}
        className="gap-2 rounded-xl glass"
      >
        <FileText className="h-4 w-4" />
        MD
      </Button>

      <Button
        variant="outline"
        size="sm"
        onClick={exportHistoryAsJSON}
        disabled={history.length === 0}
        className="gap-2 rounded-xl glass"
      >
        <FileJson className="h-4 w-4" />
        JSON
      </Button>
    </div>
  );
}
